#!/system/bin/sh
cd ${0%/*}
module_dir="/data/adb/modules/ANetProxy"
export PATH="/data/adb/ap/bin:/data/adb/ksu/bin:/data/adb/magisk:$PATH"

QUIC="disable"
CROND_TASK="disable"
IPV6="true"
IP4V="iptables -w 100"
IP6V="ip6tables -w 100"
CORE_UID=0
CORE_GID=3005
FWMARK="0x10000000/0xFFFFFFFF"
TABLE=1000
CHAIN_NAME="NetProxy"
PROXY_MODE="whitelist"
CORE_DIR="$(dirname "$(pwd)")/binary"
CORE="$(dirname "$(pwd)")/binary/xray"
CONF_DIR="$(dirname "$(pwd)")/conf"
LOG_DIR="$(dirname "$(pwd)")/log"

for file in $(find "${CONF_DIR}" -type f -name "*.json" -not -name "api.json"); do
    if awk '/"inbounds"/ {found=1; exit} END {exit !found}' "${file}"; then
      base_file="${CONF_DIR}/$(basename "${file}")"
      break
    fi
done
tport=$(awk -F'":' '/"inbounds"/ {in_block=1} in_block && /"port"/ {gsub(/[[:space:]]/, "", $2); match($2, /^[0-9]+/); print substr($2, RSTART, RLENGTH); exit}' ${base_file})

toast() {
  local events=$1
  am start -n re.tools/.main --es toast "${events}" >/dev/null 2>&1
}

check_files_complete() {
  files=("${CORE##*/}" "geosite.dat" "geoip.dat")
  missing=()
  for F in "${files[@]}"; do
    [ ! -f "${CORE_DIR}/${F}" ] && missing+=("${F}")
  done
  if [ "${#missing[@]}" -gt 0 ]; then
    toast "❌Missing: ${missing[*]}"
    exit 1
  fi
  chmod -R 755 ${CORE_DIR}
  chown -R root:net_admin ${CORE_DIR}
}

case "${PROXY_MODE}" in
"whitelist")
  package_list=(com.google.android.youtube com.google.android.gms com.google.android.gsf com.android.vending com.google.android.configupdater com.android.providers.downloads com.google.android.webview com.google.android.googlequicksearchbox com.google.android.onetimeinitializer com.google.android.printservice.recommendation com.google.android.apps.maps com.google.android.apps.translate com.google.android.inputmethod.latin com.google.android.apps.authenticator2 io.github.chsbuffer.revancedxposed me.weishu.kernelsu com.android.chrome com.twitter.android com.github.android com.reddit.frontpage com.openai.chatgpt com.xingin.xhs org.thunderdog.challegram bin.mt.plus bin.mt.termex com.valvesoftware.android.steam.community com.android.shell)
  ;;
"blacklist")
  package_list=()
  ;;
esac

appclones=()

intranet4=(0.0.0.0/8 10.0.0.0/8 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16 172.16.0.0/12 192.0.0.0/24 192.0.2.0/24 192.88.99.0/24 192.168.0.0/16 198.51.100.0/24 203.0.113.0/24 224.0.0.0/4 240.0.0.0/4 255.0.0.0/4 255.255.255.0/24 255.255.255.255/32)
intranet6=(::/127 2408:8000::/20 2409:8000::/20 240a:4000::/21 240e::/18 fc00::/7 fe80::/10 ff00::/8)

AIDs=()

fw_clean() {
  local ipt_cmd="${1}"
  ${ipt_cmd} -S 2>/dev/null |
    awk '$1=="-N" { print $2 }' |
    sort -u |
    while read -r chain; do
      ${ipt_cmd} -L "${chain}" -n >/dev/null 2>&1 || continue
      ${ipt_cmd} -L "${chain}" -n --line-numbers 2>/dev/null |
        awk '$2=="REJECT" || $2=="DROP" { print $1 }' |
        sort -rn |
        while read -r num; do
          ${ipt_cmd} -w -D "${chain}" "${num}"
        done
    done
}

init_uids() {
  uid=""
  uids=()
  if [ -f "${LOG_DIR}/uids.list" ]; then
    rm "${LOG_DIR}/uids.list"
  fi

  for package_name in "${package_list[@]}"; do
    uid=$(awk -v package="${package_name}" '$1 == package {print $2}' /data/system/packages.list)
    if [ -n "${uid}" ]; then
      uids+=("${uid}")
      echo "${package_name}: ${uid}" >>"${LOG_DIR}/uids.list"
    fi
  done

  for package_name in "${appclones[@]}"; do
    uid=$(awk -v package="${package_name}" '$1 == package {print $2}' /data/system/packages.list)
    if [ -n "${uid}" ]; then
      uid=$((999 * 100000 + uid))
      uids+=("${uid}")
      echo "${package_name}: ${uid}" >>"${LOG_DIR}/uids.list"
    fi
  done

  sort -t ':' -k2 -n "${LOG_DIR}/uids.list" -o "${LOG_DIR}/uids.list"
  uids=($(printf "%s\n" "${uids[@]}" | sort -n | uniq))
}

cron_task() {
  if [[ "${CROND_TASK}" == "enable" ]]; then
    crontab_file="$(pwd)/root"
    if pgrep -f "busybox crond -c $(pwd)/" >/dev/null; then
      kill -9 $(pgrep -f "busybox crond -c $(pwd)/")
    fi
    echo "0 3 * * * touch ${module_dir}/disable && sleep 3 && rm ${module_dir}/disable" > "${crontab_file}"
    nohup busybox crond -c $(pwd)/ >/dev/null 2>&1 &
    PID_CRON=$(pgrep -f "busybox crond -c $(pwd)/")
  else
    return
  fi
}

pid-record() {
  [ -n "${PID_CORE}" ] && echo "pid_${CORE##*/}:${PID_CORE}" >>"${LOG_DIR}/pid.txt"
  [ -n "${PID_CRON}" ] && echo "pid_cron:${PID_CRON}" >>"${LOG_DIR}/pid.txt"
}

# Last edited: 2026.4.13