#!/system/bin/sh
module_dir="/data/adb/modules/ANetProxy"
ini_dir="$(cd "$(dirname "$0")" && pwd)"
PARENT_DIR="$(dirname "$(cd "$(dirname "$0")" && pwd)")"
export PATH="/data/adb/ap/bin:/data/adb/ksu/bin:/data/adb/magisk:$PATH"

tport=1536
IPv4="iptables -w 100"
IPv6="ip6tables -w 100"
IPv6_enable="disable"
FWMARK="0x10000000/0xFFFFFFFF"
TABLE=0x3e8
CHAIN_NAME="NetProxy"
PROXY_MODE="whitelist"
QUIC="disable"

CORE_UID=0
CORE_GID=3005
CORE_DIR="${PARENT_DIR}/binary"
CORE="${CORE_DIR}/xray"
CONF_DIR="${PARENT_DIR}/conf"
LOG_DIR="${PARENT_DIR}/log"

CROND_TASK="disable"

case "${PROXY_MODE}" in
"whitelist")
  package_list=(com.android.shell com.android.providers.downloads com.google.android.apps.translate io.github.chsbuffer.revancedxposed com.google.android.gsf com.google.android.printservice.recommendation com.google.android.onetimeinitializer com.google.android.configupdater com.android.vending com.google.android.googlequicksearchbox com.google.android.webview me.weishu.kernelsu com.xhey.xcamera org.thunderdog.challegram com.android.chrome bin.mt.termex com.twitter.android com.google.android.inputmethod.latin com.github.android com.google.android.gms com.google.android.apps.authenticator2 com.reddit.frontpage com.google.android.apps.maps bin.mt.plus com.google.android.youtube)
  ;;
"blacklist")
  package_list=()
  ;;
esac

appclones=()

# IPv4 network segment
intranet4=(0.0.0.0/8 10.0.0.0/8 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16 172.16.0.0/12 192.0.0.0/24 192.0.2.0/24 192.88.99.0/24 192.168.0.0/16 198.51.100.0/24 203.0.113.0/24 224.0.0.0/4 240.0.0.0/4 255.0.0.0/4 255.255.255.0/24 255.255.255.255/32)

# IPv6 network segment
intranet6=(::/127 2408:8000::/20 2409:8000::/20 240a:4000::/21 240e::/18 fc00::/7 fe80::/10 ff00::/8)

toast() {
  local events=$1
  am start -n re.tools/.main --es toast "${events}" >/dev/null 2>&1
}

ensure_xray_assets() {
  files=("${CORE##*/}" "geosite.dat" "geoip.dat")
  missing=()
  for F in "${files[@]}"; do
    [ ! -f "${CORE_DIR}/${F}" ] && missing+=("${F}")
  done
  if [ "${#missing[@]}" -gt 0 ]; then
    toast "❌Missing: ${missing[*]}"
    exit 1
  fi
  chmod -R 755 ${CORE_DIR}
  chown -R root:net_admin ${CORE_DIR}
}

fw_clean() {
  local ipt_cmd="${1}"
  ${ipt_cmd} -S 2>/dev/null |
    awk '$1=="-N" { print $2 }' |
    sort -u |
    while read -r chain; do
      ${ipt_cmd} -L "${chain}" -n >/dev/null 2>&1 || continue
      ${ipt_cmd} -L "${chain}" -n --line-numbers 2>/dev/null |
        awk '$2=="REJECT" || $2=="DROP" { print $1 }' |
        sort -rn |
        while read -r num; do
          ${ipt_cmd} -w -D "${chain}" "${num}"
        done
    done
}

find_packages_uid() {
  uids=()
  local out_file="${LOG_DIR}/uids.list"
  local tmp_file=$(mktemp)

  eval "$( {
    [ ${#package_list[@]} -gt 0 ] && printf "TARGET MAIN %s\n" "${package_list[@]}"
    [ ${#appclones[@]} -gt 0 ] && printf "TARGET CLONE %s\n" "${appclones[@]}"
    sed 's/^/FILE /' /data/system/packages.list 2>/dev/null
  } | awk -v tmp="$tmp_file" '
  $1 == "TARGET" {
    if ($2 == "MAIN") main_pkgs[$3] = 1
    if ($2 == "CLONE") clone_pkgs[$3] = 1
    next
  }
  $1 == "FILE" {
    pkg = $2
    uid = $3
    if (pkg in main_pkgs) {
      printf "uids+=(\"%s\");\n", uid
      print pkg, uid >> tmp
    }
    if (pkg in clone_pkgs) {
      clone_uid = 999 * 100000 + uid
      printf "uids+=(\"%s\");\n", clone_uid
      print pkg, clone_uid >> tmp
    }
  }
  ' )"

  uids=($(printf "%s\n" "${uids[@]}" | sort -n | uniq))
  sort -k2 -n -u "$tmp_file" > "$out_file"
  rm -f "$tmp_file"
}

cron_task() {
  if [[ "${CROND_TASK}" == "enable" ]]; then
    crontab_file="${ini_dir}/root"
    if pgrep -f "busybox crond -c ${ini_dir}/" >/dev/null; then
      kill -9 $(pgrep -f "busybox crond -c ${ini_dir}/")
    fi
    echo "0 3 * * * touch ${module_dir}/disable && sleep 3 && rm ${module_dir}/disable" > "${crontab_file}"
    nohup busybox crond -c ${ini_dir}/ >/dev/null 2>&1 &
    PID_CRON=$(pgrep -f "busybox crond -c ${ini_dir}/")
    [ -n "${PID_CRON}" ] && echo "pid_cron:${PID_CRON}" >>"${LOG_DIR}/pid.txt"
  else
    return
  fi
}
